#!/bin/bash
#
# Gate 6: Artifact + Traceability
# ================================
# Generates artifacts and metadata for tracking
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "================================================"
echo "📦 Gate 6: Artifact + Traceability"
echo "================================================"
echo ""

cd "$PROJECT_ROOT"

# Create artifacts directory
ARTIFACTS_DIR="/tmp/ci_artifacts"
mkdir -p "$ARTIFACTS_DIR"

echo "📁 Artifacts directory: $ARTIFACTS_DIR"
echo ""

# Get metadata
COMMIT_SHA=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "📊 Collecting metadata..."
echo "  Commit: $COMMIT_SHA"
echo "  Branch: $BRANCH"
echo "  Python: $PYTHON_VERSION"
echo "  Time: $TIMESTAMP"
echo ""

# Generate reality_report.json
echo "📝 Generating reality_report.json..."
cat > "$ARTIFACTS_DIR/reality_report.json" << EOF
{
  "commit_sha": "$COMMIT_SHA",
  "branch": "$BRANCH",
  "python_version": "$PYTHON_VERSION",
  "timestamp": "$TIMESTAMP",
  "gates": {
    "gate_0": {
      "name": "Repo Integrity",
      "passed": null,
      "duration_s": null
    },
    "gate_1": {
      "name": "Format/Lint",
      "passed": null,
      "duration_s": null
    },
    "gate_2": {
      "name": "Type Safety",
      "passed": null,
      "duration_s": null
    },
    "gate_3": {
      "name": "Phase-1 Reality Tests",
      "passed": null,
      "duration_s": null,
      "tests": 137
    },
    "gate_4": {
      "name": "Anti-Mock Proof",
      "passed": null,
      "duration_s": null
    },
    "gate_5": {
      "name": "Determinism Proof",
      "passed": null,
      "duration_s": null
    },
    "gate_6": {
      "name": "Artifact + Traceability",
      "passed": true,
      "duration_s": 0
    }
  },
  "total_duration_s": null,
  "status": "IN_PROGRESS"
}
EOF

echo -e "${GREEN}✓ reality_report.json created${NC}"

# Generate CI summary
echo ""
echo "📝 Generating ci_summary.md..."
cat > "$ARTIFACTS_DIR/ci_summary.md" << EOF
# CI Summary

**Commit:** \`$COMMIT_SHA\`  
**Branch:** \`$BRANCH\`  
**Python:** $PYTHON_VERSION  
**Timestamp:** $TIMESTAMP

## Gates

| Gate | Name | Status |
|------|------|--------|
| 0 | Repo Integrity | Pending |
| 1 | Format/Lint | Pending |
| 2 | Type Safety | Pending |
| 3 | Phase-1 Reality Tests (137 tests) | Pending |
| 4 | Anti-Mock Proof | Pending |
| 5 | Determinism Proof | Pending |
| 6 | Artifact + Traceability | ✅ |

## Files

- \`reality_report.json\` - Machine-readable metadata
- \`ci_summary.md\` - Human-readable summary  
- \`junit.xml\` - Test results (generated by Gate 3)

## Next Steps

Run all gates:
\`\`\`bash
./scripts/ci_run_first_step.sh
\`\`\`
EOF

echo -e "${GREEN}✓ ci_summary.md created${NC}"

# Copy junit.xml if it exists
echo ""
if [ -f /tmp/gate3_junit.xml ]; then
    cp /tmp/gate3_junit.xml "$ARTIFACTS_DIR/junit.xml"
    echo -e "${GREEN}✓ junit.xml copied${NC}"
else
    echo -e "${YELLOW}⚠️  junit.xml not found (run Gate 3 first)${NC}"
fi

# List artifacts
echo ""
echo "📦 Artifacts created:"
ls -lh "$ARTIFACTS_DIR"

echo ""
echo "================================================"
echo -e "${GREEN}✅ Gate 6: PASSED${NC}"
echo "Artifacts generated successfully."
echo ""
echo "View artifacts:"
echo "  cat $ARTIFACTS_DIR/reality_report.json"
echo "  cat $ARTIFACTS_DIR/ci_summary.md"

exit 0






